### ISSUE TITLE
Use openshift/origin-cli

### ISSUE THREAD

**Issue by bliemli** [appuio/container-oc#10]
I just discovered the `openshift/origin-cli` image, oldest image tag though is `v3.10`, but we could replace 3.10 and newer images with this one.

Sources:
https://hub.docker.com/r/openshift/origin-cli/ 
https://github.com/openshift/origin/tree/master/images/cli

**Comment by bittner** [comment]
In the meantime, our image has developed into a "generic CI/CD tooling" image. It's not just `oc` anymore.

We may want to use that image as a base image, though, in the future. Do you know where the source code for the image has gone now? (The second link above is dangling.)

**Comment by ccremer** [comment]
Closed since this issue has gone stale.
