### ISSUE TITLE
Release v4.16

### ISSUE THREAD

**Issue by elchenberg** [appuio/container-oc#111]
It would be nice to get a v4.16 release of the image because the `oc` binary used in the v4.15 version of the image has 5 known critical vulnerabilities and 15 high severity vulnerabilities (according to [Trivy](https://github.com/aquasecurity/trivy), but to be fair, some of those vulnerabilities might be false alerts) while the latest v4.16 only has 1 critical vulnerability and 0 high severity vulnerabilities.

**Comment by tobru** [comment]
Done in #113
