### ISSUE TITLE
Can we use a smaller base image?

### ISSUE THREAD

**Issue by bittner** [appuio/container-oc#6]
Do we need CentOS for [this image](https://github.com/appuio/container-oc/blob/master/src/Dockerfile#L1)? This results in a fairly big footprint.

Wouldn't the `oc` binary run the same way on an ubuntu-minimal or alpine base image?

**Comment by mhutter** [comment]
We already tried using an alpine-based image but failed (due to the `oc` binaries not being compatible with `musl` IIRC).

Using an ubuntu minimal image might be an option

**Comment by tobru** [comment]
We're using CentOS because this is the official distro for Origin / OKD and therefore best supported.
