### ISSUE TITLE
Integrate helm-diff plugin

### ISSUE THREAD

**Issue by bittner** [appuio/container-oc#61]
Applying a new version of a helm chart using automation is a slightly intransparent process. We don't know what the helm chart will apply in the target cluster until it's "too late".

[helm-diff](https://github.com/databus23/helm-diff) tries to address that problem by allowing to produce a diff of the current state in the cluster and what the updated helm chart would produce. It's a plugin for helm 2 and 3.

[Adding this plugin](https://github.com/databus23/helm-diff/releases) would make the `oc` container image more useful for controlled processes involving helm. Would you be open to accept a related PR?

**Comment by ccremer** [comment]
There is a more helm-specific image here with even more plugins installed: https://github.com/appuio/container-helm

Does that cover your workflow?

**Comment by bittner** [comment]
Sound promising. I'll take a look at it. Thank you!
