### ISSUE TITLE
Integrate sponge (moreutils RPM package)

### ISSUE THREAD

**Issue by bittner** [appuio/container-oc#62]
The `oc` container image ships with the `tee` command line utility that allows to elegantly use the `envsubst` idiom on Kustomize configurations for in-place substitutions of placeholders (as an alternative to the opaque `kustomize edit` command).

Example: (the `kustomization.yaml` can contain environment variables such as `$CI_FOO`)

```yaml
script:
- envsubst < kustomization.yaml | tee kustomization.yaml
```

Unfortunately, `tee` introduces a race condition when used with pipes [as explained on StackOverflow](https://stackoverflow.com/questions/60546292/usage-of-envsubst-combined-with-tee-randomly-results-in-an-empty-file). The `sponge` command solves this issue by opening the target file only after having exhausted stdout.

`sponge` is included in the[ `moreutils` RPM package](https://centos.pkgs.org/7/epel-x86_64/moreutils-0.49-2.el7.x86_64.rpm.html). This is a small package, but helps to resolve common big issues that otherwise need to be solved in non-elegant ways.

Would you accept a PR that adds installing the `moreutils` package in the `Dockerfile`?

**Comment by ccremer** [comment]
sure! managing dynamic config with kustomize is a real pain...
