### ISSUE TITLE
Migrate away from CentOS base image

### ISSUE THREAD

**Issue by mhutter** [appuio/container-oc#90]
The centos base image has been deprecated: https://hub.docker.com/_/centos (also see #87 )

We should move to something supported.
Keep in mind that this potentially breaks downstream projects like [appuio/container-helm](https://github.com/appuio/container-helm)

**Comment by tobru** [comment]
We might want to use [UBI](https://developers.redhat.com/products/rhel/ubi) to stay in the Red Hat ecosystem, as this container is all about OpenShift.
